url: lergonomica.github.io
baseurl: 

# Site settings
title: l'ergonomica
email: lergonomica1@google.com
description: "Soluzioni per vivere in autonomia"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Via Gian Leonardo Ceruso, 20 00147 Roma 

# Build settings
markdown: kramdown
permalink: pretty

telephone:
copyright:

# API settings
google_api_key: AIzaSyAHhpx4Act7Ue0BY5o6k0Hs763uiUJ3R2k
